eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
server:
  port: 0
spring:
  application:
    name: projectservice
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=projectservice
    username: postgres
    password: rootaye2
    driver-class-name: org.postgresql.Driver
grpc:
  server:
    port: 0