spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone: "http://localhost:8761/eureka"
    fetch-registry: true
    register-with-eureka: true
